"""knowledge ingest job recipient

Revision ID: 03af17f40250
Revises: 1fcf9edaca25
Create Date: 2026-08-30 05:58:57.150426
"""
from alembic import op
import sqlalchemy as sa


revision = '03af17f40250'
down_revision = '1fcf9edaca25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_ingest_jobs', sa.Column('recipient', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_ingest_jobs', 'recipient')
    # ### end Alembic commands ###
