"""knowledge pending attachments

Revision ID: 1fcf9edaca25
Revises: b0ff2dca9936
Create Date: 2026-08-29 21:07:21.879961
"""
from alembic import op
import sqlalchemy as sa


revision = '1fcf9edaca25'
down_revision = 'b0ff2dca9936'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_pending_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('spool_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_pending_attachments'))
    )
    op.create_index('ix_knowledge_pending_attachments_channel_created', 'knowledge_pending_attachments', ['channel', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_pending_attachments_channel_created', table_name='knowledge_pending_attachments')
    op.drop_table('knowledge_pending_attachments')
    # ### end Alembic commands ###
