"""helm knowledge tables

Revision ID: b0ff2dca9936
Revises: f12e419c664b
Create Date: 2026-08-29 17:16:26.498638
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'b0ff2dca9936'
down_revision = 'f12e419c664b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_answer_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('paid_ai_used', sa.Boolean(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('local_model', sa.String(length=128), nullable=True),
    sa.Column('cloud_model', sa.String(length=128), nullable=True),
    sa.Column('escalation_reason', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_answer_runs'))
    )
    op.create_index('ix_knowledge_answer_runs_created', 'knowledge_answer_runs', ['created_at'], unique=False)
    op.create_table('knowledge_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_sha256', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sensitivity', sa.String(length=32), nullable=False),
    sa.Column('trust', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('supersedes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contradicts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_notes')),
    sa.UniqueConstraint('slug', name='uq_knowledge_notes_slug')
    )
    op.create_table('knowledge_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('raw_path', sa.Text(), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('parser', sa.String(length=32), nullable=True),
    sa.Column('sensitivity', sa.String(length=32), nullable=False),
    sa.Column('trust', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_sources')),
    sa.UniqueConstraint('sha256', name='uq_knowledge_sources_sha256')
    )
    op.create_index('ix_knowledge_sources_domain_status', 'knowledge_sources', ['domain', 'status'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('time_start_ms', sa.Integer(), nullable=True),
    sa.Column('time_end_ms', sa.Integer(), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], name=op.f('fk_knowledge_chunks_source_id_knowledge_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunks')),
    sa.UniqueConstraint('source_id', 'ordinal', name='uq_knowledge_chunks_source_ordinal')
    )
    op.create_index('ix_knowledge_chunks_tsv', 'knowledge_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('knowledge_ingest_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], name=op.f('fk_knowledge_ingest_jobs_source_id_knowledge_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_ingest_jobs'))
    )
    op.create_index('ix_knowledge_ingest_jobs_status', 'knowledge_ingest_jobs', ['status', 'created_at'], unique=False)
    op.create_table('knowledge_relations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_id', sa.String(length=128), nullable=False),
    sa.Column('to_id', sa.String(length=128), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('evidence_type', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], name=op.f('fk_knowledge_relations_source_id_knowledge_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_relations'))
    )
    op.create_index('ix_knowledge_relations_from', 'knowledge_relations', ['from_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_relations_from', table_name='knowledge_relations')
    op.drop_table('knowledge_relations')
    op.drop_index('ix_knowledge_ingest_jobs_status', table_name='knowledge_ingest_jobs')
    op.drop_table('knowledge_ingest_jobs')
    op.drop_index('ix_knowledge_chunks_tsv', table_name='knowledge_chunks', postgresql_using='gin')
    op.drop_table('knowledge_chunks')
    op.drop_index('ix_knowledge_sources_domain_status', table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_table('knowledge_notes')
    op.drop_index('ix_knowledge_answer_runs_created', table_name='knowledge_answer_runs')
    op.drop_table('knowledge_answer_runs')
    # ### end Alembic commands ###
