"""knowledge tenancy v3.8

Revision ID: ef1ba5467e14
Revises: f6617c6739ee
Create Date: 2026-08-30 15:12:53.430986
"""
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ef1ba5467e14'
down_revision = 'f6617c6739ee'
branch_labels = None
depends_on = None

#: v3.8 §14.2/CONTINUE_HELM_v3.7_TO_v3.8.md: "Backfill all existing corpus
#: /batches/topics/domains to SYSTEM_OWNER without reparse/rechunk/re-
#: embedding" — каждая из этих таблиц уже существовала до v3.8 и получает
#: nullable knowledge_user_id этой же миграцией; без backfill все старые
#: строки остались бы NULL и стали бы невидимы, как только RLS-политики
#: (следующий заход) начнут фильтровать по этому полю.
_BACKFILL_TABLES = (
    "knowledge_sources", "knowledge_chunks", "knowledge_notes", "knowledge_relations",
    "knowledge_ingest_jobs", "knowledge_pending_attachments", "knowledge_ingest_batches",
    "knowledge_batch_items", "knowledge_answer_runs",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('storage_quota_bytes', sa.BigInteger(), nullable=True),
    sa.Column('daily_ingest_quota_bytes', sa.BigInteger(), nullable=True),
    sa.Column('allow_paid_ai', sa.Boolean(), nullable=False),
    sa.Column('style_profile_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_users'))
    )
    op.create_table('knowledge_channel_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('external_user_id', sa.String(length=64), nullable=False),
    sa.Column('external_chat_id', sa.String(length=64), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_user_id'], ['knowledge_users.id'], name=op.f('fk_knowledge_channel_identities_knowledge_user_id_knowledge_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_channel_identities')),
    sa.UniqueConstraint('channel', 'external_user_id', name='uq_knowledge_channel_identities_channel_user')
    )
    op.create_index('ix_knowledge_channel_identities_user', 'knowledge_channel_identities', ['knowledge_user_id'], unique=False)
    op.create_table('knowledge_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expected_external_user_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_user_id'], ['knowledge_users.id'], name=op.f('fk_knowledge_invites_knowledge_user_id_knowledge_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_invites')),
    sa.UniqueConstraint('token_hash', name='uq_knowledge_invites_token_hash')
    )
    op.create_table('knowledge_memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('canonical_text', sa.Text(), nullable=False),
    sa.Column('display_label', sa.String(length=255), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('domain', sa.String(length=32), nullable=True),
    sa.Column('sensitivity', sa.String(length=32), nullable=False),
    sa.Column('trust', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('supersedes_memory_id', sa.Uuid(), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('origin_channel', sa.String(length=32), nullable=True),
    sa.Column('origin_message_id', sa.String(length=128), nullable=True),
    sa.Column('origin_kind', sa.String(length=8), nullable=True),
    sa.Column('graph_status', sa.String(length=32), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_user_id'], ['knowledge_users.id'], name=op.f('fk_knowledge_memories_knowledge_user_id_knowledge_users')),
    sa.ForeignKeyConstraint(['supersedes_memory_id'], ['knowledge_memories.id'], name=op.f('fk_knowledge_memories_supersedes_memory_id_knowledge_memories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_memories'))
    )
    op.create_index('ix_knowledge_memories_tsv', 'knowledge_memories', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_knowledge_memories_user_dedup', 'knowledge_memories', ['knowledge_user_id', 'dedup_hash'], unique=False)
    op.create_index('ix_knowledge_memories_user_status', 'knowledge_memories', ['knowledge_user_id', 'status'], unique=False)
    op.create_table('knowledge_user_usage',
    sa.Column('knowledge_user_id', sa.Uuid(), nullable=False),
    sa.Column('storage_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sources_count', sa.Integer(), nullable=False),
    sa.Column('memories_count', sa.Integer(), nullable=False),
    sa.Column('queued_jobs', sa.Integer(), nullable=False),
    sa.Column('ingest_bytes_today', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_user_id'], ['knowledge_users.id'], name=op.f('fk_knowledge_user_usage_knowledge_user_id_knowledge_users')),
    sa.PrimaryKeyConstraint('knowledge_user_id', name=op.f('pk_knowledge_user_usage'))
    )
    op.add_column('knowledge_answer_runs', sa.Column('knowledge_user_id', sa.Uuid(), nullable=True))
    op.create_index('ix_knowledge_answer_runs_user', 'knowledge_answer_runs', ['knowledge_user_id'], unique=False)
    op.create_foreign_key(op.f('fk_knowledge_answer_runs_knowledge_user_id_knowledge_users'), 'knowledge_answer_runs', 'knowledge_users', ['knowledge_user_id'], ['id'])
    op.add_column('knowledge_batch_items', sa.Column('knowledge_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_knowledge_batch_items_knowledge_user_id_knowledge_users'), 'knowledge_batch_items', 'knowledge_users', ['knowledge_user_id'], ['id'])
    op.add_column('knowledge_chunks', sa.Column('knowledge_user_id', sa.Uuid(), nullable=True))
    op.create_index('ix_knowledge_chunks_user', 'knowledge_chunks', ['knowledge_user_id'], unique=False)
    op.create_foreign_key(op.f('fk_knowledge_chunks_knowledge_user_id_knowledge_users'), 'knowledge_chunks', 'knowledge_users', ['knowledge_user_id'], ['id'])
    op.add_column('knowledge_ingest_batches', sa.Column('knowledge_user_id', sa.Uuid(), nullable=True))
    op.drop_index('ix_knowledge_ingest_batches_archive_sha256', table_name='knowledge_ingest_batches')
    op.create_index('ix_knowledge_ingest_batches_user_sha256', 'knowledge_ingest_batches', ['knowledge_user_id', 'archive_sha256'], unique=False)
    op.create_foreign_key(op.f('fk_knowledge_ingest_batches_knowledge_user_id_knowledge_users'), 'knowledge_ingest_batches', 'knowledge_users', ['knowledge_user_id'], ['id'])
    op.add_column('knowledge_ingest_jobs', sa.Column('knowledge_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_knowledge_ingest_jobs_knowledge_user_id_knowledge_users'), 'knowledge_ingest_jobs', 'knowledge_users', ['knowledge_user_id'], ['id'])
    op.add_column('knowledge_notes', sa.Column('knowledge_user_id', sa.Uuid(), nullable=True))
    op.drop_constraint('uq_knowledge_notes_slug', 'knowledge_notes', type_='unique')
    op.create_unique_constraint('uq_knowledge_notes_user_slug', 'knowledge_notes', ['knowledge_user_id', 'slug'])
    op.create_foreign_key(op.f('fk_knowledge_notes_knowledge_user_id_knowledge_users'), 'knowledge_notes', 'knowledge_users', ['knowledge_user_id'], ['id'])
    op.add_column('knowledge_pending_attachments', sa.Column('knowledge_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_knowledge_pending_attachments_knowledge_user_id_knowledge_users'), 'knowledge_pending_attachments', 'knowledge_users', ['knowledge_user_id'], ['id'])
    op.add_column('knowledge_relations', sa.Column('knowledge_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_knowledge_relations_knowledge_user_id_knowledge_users'), 'knowledge_relations', 'knowledge_users', ['knowledge_user_id'], ['id'])
    op.add_column('knowledge_sources', sa.Column('knowledge_user_id', sa.Uuid(), nullable=True))
    op.drop_constraint('uq_knowledge_sources_sha256', 'knowledge_sources', type_='unique')
    op.create_index('ix_knowledge_sources_user', 'knowledge_sources', ['knowledge_user_id'], unique=False)
    op.create_unique_constraint('uq_knowledge_sources_user_sha256', 'knowledge_sources', ['knowledge_user_id', 'sha256'])
    op.create_foreign_key(op.f('fk_knowledge_sources_knowledge_user_id_knowledge_users'), 'knowledge_sources', 'knowledge_users', ['knowledge_user_id'], ['id'])
    # ### end Alembic commands ###

    # Backfill: ровно один SYSTEM_OWNER, все существующие Knowledge-строки —
    # его (см. _BACKFILL_TABLES выше). id генерируется здесь, а не берётся
    # из кода приложения — миграция не импортирует helm_core.
    conn = op.get_bind()
    owner_id = uuid.uuid4()
    conn.execute(
        sa.text(
            "INSERT INTO knowledge_users "
            "(id, role, status, locale, timezone, allow_paid_ai, style_profile_version, created_at) "
            "VALUES (:id, 'SYSTEM_OWNER', 'ACTIVE', 'ru', 'Europe/Moscow', false, 1, now())"
        ),
        {"id": owner_id},
    )
    for table in _BACKFILL_TABLES:
        conn.execute(
            sa.text(f"UPDATE {table} SET knowledge_user_id = :id WHERE knowledge_user_id IS NULL"),
            {"id": owner_id},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_knowledge_sources_knowledge_user_id_knowledge_users'), 'knowledge_sources', type_='foreignkey')
    op.drop_constraint('uq_knowledge_sources_user_sha256', 'knowledge_sources', type_='unique')
    op.drop_index('ix_knowledge_sources_user', table_name='knowledge_sources')
    op.create_unique_constraint('uq_knowledge_sources_sha256', 'knowledge_sources', ['sha256'])
    op.drop_column('knowledge_sources', 'knowledge_user_id')
    op.drop_constraint(op.f('fk_knowledge_relations_knowledge_user_id_knowledge_users'), 'knowledge_relations', type_='foreignkey')
    op.drop_column('knowledge_relations', 'knowledge_user_id')
    op.drop_constraint(op.f('fk_knowledge_pending_attachments_knowledge_user_id_knowledge_users'), 'knowledge_pending_attachments', type_='foreignkey')
    op.drop_column('knowledge_pending_attachments', 'knowledge_user_id')
    op.drop_constraint(op.f('fk_knowledge_notes_knowledge_user_id_knowledge_users'), 'knowledge_notes', type_='foreignkey')
    op.drop_constraint('uq_knowledge_notes_user_slug', 'knowledge_notes', type_='unique')
    op.create_unique_constraint('uq_knowledge_notes_slug', 'knowledge_notes', ['slug'])
    op.drop_column('knowledge_notes', 'knowledge_user_id')
    op.drop_constraint(op.f('fk_knowledge_ingest_jobs_knowledge_user_id_knowledge_users'), 'knowledge_ingest_jobs', type_='foreignkey')
    op.drop_column('knowledge_ingest_jobs', 'knowledge_user_id')
    op.drop_constraint(op.f('fk_knowledge_ingest_batches_knowledge_user_id_knowledge_users'), 'knowledge_ingest_batches', type_='foreignkey')
    op.drop_index('ix_knowledge_ingest_batches_user_sha256', table_name='knowledge_ingest_batches')
    op.create_index('ix_knowledge_ingest_batches_archive_sha256', 'knowledge_ingest_batches', ['archive_sha256'], unique=False)
    op.drop_column('knowledge_ingest_batches', 'knowledge_user_id')
    op.drop_constraint(op.f('fk_knowledge_chunks_knowledge_user_id_knowledge_users'), 'knowledge_chunks', type_='foreignkey')
    op.drop_index('ix_knowledge_chunks_user', table_name='knowledge_chunks')
    op.drop_column('knowledge_chunks', 'knowledge_user_id')
    op.drop_constraint(op.f('fk_knowledge_batch_items_knowledge_user_id_knowledge_users'), 'knowledge_batch_items', type_='foreignkey')
    op.drop_column('knowledge_batch_items', 'knowledge_user_id')
    op.drop_constraint(op.f('fk_knowledge_answer_runs_knowledge_user_id_knowledge_users'), 'knowledge_answer_runs', type_='foreignkey')
    op.drop_index('ix_knowledge_answer_runs_user', table_name='knowledge_answer_runs')
    op.drop_column('knowledge_answer_runs', 'knowledge_user_id')
    op.drop_table('knowledge_user_usage')
    op.drop_index('ix_knowledge_memories_user_status', table_name='knowledge_memories')
    op.drop_index('ix_knowledge_memories_user_dedup', table_name='knowledge_memories')
    op.drop_index('ix_knowledge_memories_tsv', table_name='knowledge_memories', postgresql_using='gin')
    op.drop_table('knowledge_memories')
    op.drop_table('knowledge_invites')
    op.drop_index('ix_knowledge_channel_identities_user', table_name='knowledge_channel_identities')
    op.drop_table('knowledge_channel_identities')
    op.drop_table('knowledge_users')
    # ### end Alembic commands ###
