"""initial schema

Revision ID: f12e419c664b
Revises: 
Create Date: 2026-08-27 13:39:46.781193
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'f12e419c664b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_trust',
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('current_level', sa.String(length=16), nullable=False),
    sa.Column('supervised_success', sa.Integer(), nullable=False),
    sa.Column('last_incident_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_by', sa.String(length=64), nullable=True),
    sa.CheckConstraint('(promoted_at IS NULL) OR (promoted_by IS NOT NULL)', name=op.f('ck_action_trust_promotion_requires_owner')),
    sa.CheckConstraint('supervised_success >= 0', name=op.f('ck_action_trust_supervised_success_non_negative')),
    sa.PrimaryKeyConstraint('action_type', name=op.f('pk_action_trust'))
    )
    op.create_table('budget_daily',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('spent_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('soft_limit_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('hard_limit_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('kill_switch_active', sa.Boolean(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_daily')),
    sa.UniqueConstraint('date', 'scope', name='uq_budget_daily_date_scope')
    )
    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('review_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_table('metrics_ts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics_ts'))
    )
    op.create_index('ix_metrics_ts_metric_ts', 'metrics_ts', ['metric', 'timestamp'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('recipient', sa.String(length=128), nullable=False),
    sa.Column('payload_reference', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dedup_key', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox')),
    sa.UniqueConstraint('dedup_key', name='uq_outbox_dedup_key')
    )
    op.create_table('panel_enrollment_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_panel_enrollment_tokens')),
    sa.UniqueConstraint('token_hash', name='uq_panel_enrollment_tokens_token_hash')
    )
    op.create_table('panel_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_label', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_panel_sessions'))
    )
    op.create_table('routines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('schedule', sa.String(length=64), nullable=False),
    sa.Column('profile', sa.String(length=64), nullable=True),
    sa.Column('skill', sa.String(length=128), nullable=True),
    sa.Column('budget_tier', sa.String(length=32), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routines')),
    sa.UniqueConstraint('name', name='uq_routines_name')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origin_channel', sa.String(length=32), nullable=False),
    sa.Column('origin_message_id', sa.String(length=128), nullable=True),
    sa.Column('origin_owner_id', sa.String(length=64), nullable=False),
    sa.Column('normalized_hash', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('budget_tier', sa.String(length=32), nullable=True),
    sa.Column('hermes_session_id', sa.String(length=128), nullable=True),
    sa.Column('hermes_run_id', sa.String(length=128), nullable=True),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('title_redacted', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], name=op.f('fk_tasks_parent_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index('ix_tasks_status_created', 'tasks', ['status', 'created_at'], unique=False)
    op.create_table('webauthn_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webauthn_credentials')),
    sa.UniqueConstraint('credential_id', name='uq_webauthn_credentials_credential_id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('action_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_encrypted_or_reference', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=True),
    sa.Column('precondition_version', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_redacted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('short_id', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_approvals_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals')),
    sa.UniqueConstraint('idempotency_key', name='uq_approvals_idempotency_key'),
    sa.UniqueConstraint('short_id', name='uq_approvals_short_id')
    )
    op.create_index('ix_approvals_status_expires', 'approvals', ['status', 'expires_at'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('sensitivity', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_artifacts_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_table('channel_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('external_message_id', sa.String(length=128), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('normalized_hash', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_channel_events_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_events')),
    sa.UniqueConstraint('channel', 'external_message_id', name='uq_channel_events_external')
    )
    op.create_index('ix_channel_events_dedup', 'channel_events', ['owner_id', 'normalized_hash', 'received_at'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('profile', sa.String(length=64), nullable=True),
    sa.Column('alias', sa.String(length=64), nullable=True),
    sa.Column('concrete_model', sa.String(length=128), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cache_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('reason_short', sa.String(length=280), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_model_runs_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_runs'))
    )
    op.create_index('ix_model_runs_ts', 'model_runs', ['timestamp'], unique=False)
    op.create_table('panel_stepup_challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('action_hashes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('challenge', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['panel_sessions.id'], name=op.f('fk_panel_stepup_challenges_session_id_panel_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_panel_stepup_challenges'))
    )
    op.create_table('task_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_redacted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_events_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_events'))
    )
    op.create_index('ix_task_events_task_ts', 'task_events', ['task_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_events_task_ts', table_name='task_events')
    op.drop_table('task_events')
    op.drop_table('panel_stepup_challenges')
    op.drop_index('ix_model_runs_ts', table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index('ix_channel_events_dedup', table_name='channel_events')
    op.drop_table('channel_events')
    op.drop_table('artifacts')
    op.drop_index('ix_approvals_status_expires', table_name='approvals')
    op.drop_table('approvals')
    op.drop_table('webauthn_credentials')
    op.drop_index('ix_tasks_status_created', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('routines')
    op.drop_table('panel_sessions')
    op.drop_table('panel_enrollment_tokens')
    op.drop_table('outbox')
    op.drop_index('ix_metrics_ts_metric_ts', table_name='metrics_ts')
    op.drop_table('metrics_ts')
    op.drop_table('decisions')
    op.drop_table('budget_daily')
    op.drop_table('action_trust')
    # ### end Alembic commands ###
