"""knowledge zip batch ingest

Revision ID: f6617c6739ee
Revises: 03af17f40250
Create Date: 2026-08-30 12:48:46.211947
"""
from alembic import op
import sqlalchemy as sa


revision = 'f6617c6739ee'
down_revision = '03af17f40250'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_ingest_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('recipient', sa.String(length=128), nullable=True),
    sa.Column('archive_filename', sa.String(length=255), nullable=True),
    sa.Column('archive_mime', sa.String(length=128), nullable=True),
    sa.Column('archive_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('archive_raw_path', sa.Text(), nullable=False),
    sa.Column('archive_sha256', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=True),
    sa.Column('sensitivity', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('total_members', sa.Integer(), nullable=False),
    sa.Column('eligible_members', sa.Integer(), nullable=False),
    sa.Column('ready_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('quarantine_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count_total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_notification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_revision', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_ingest_batches'))
    )
    op.create_index('ix_knowledge_ingest_batches_archive_sha256', 'knowledge_ingest_batches', ['archive_sha256'], unique=False)
    op.create_index('ix_knowledge_ingest_batches_channel_created', 'knowledge_ingest_batches', ['channel', 'created_at'], unique=False)
    op.create_table('knowledge_batch_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('archive_member_path_original', sa.Text(), nullable=False),
    sa.Column('archive_member_name_normalized', sa.Text(), nullable=False),
    sa.Column('declared_compressed_size', sa.BigInteger(), nullable=False),
    sa.Column('declared_uncompressed_size', sa.BigInteger(), nullable=False),
    sa.Column('detected_mime', sa.String(length=128), nullable=True),
    sa.Column('member_sha256', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('source_created_by_batch', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('chunks', sa.Integer(), nullable=True),
    sa.Column('graph_status', sa.String(length=32), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail_redacted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['knowledge_ingest_batches.id'], name=op.f('fk_knowledge_batch_items_batch_id_knowledge_ingest_batches')),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], name=op.f('fk_knowledge_batch_items_source_id_knowledge_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_batch_items')),
    sa.UniqueConstraint('batch_id', 'ordinal', name='uq_knowledge_batch_items_batch_ordinal')
    )
    op.create_index('ix_knowledge_batch_items_batch_status', 'knowledge_batch_items', ['batch_id', 'status'], unique=False)
    op.add_column('knowledge_ingest_jobs', sa.Column('batch_item_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(op.f('uq_knowledge_ingest_jobs_batch_item_id'), 'knowledge_ingest_jobs', ['batch_item_id'])
    op.create_foreign_key(op.f('fk_knowledge_ingest_jobs_batch_item_id_knowledge_batch_items'), 'knowledge_ingest_jobs', 'knowledge_batch_items', ['batch_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_knowledge_ingest_jobs_batch_item_id_knowledge_batch_items'), 'knowledge_ingest_jobs', type_='foreignkey')
    op.drop_constraint(op.f('uq_knowledge_ingest_jobs_batch_item_id'), 'knowledge_ingest_jobs', type_='unique')
    op.drop_column('knowledge_ingest_jobs', 'batch_item_id')
    op.drop_index('ix_knowledge_batch_items_batch_status', table_name='knowledge_batch_items')
    op.drop_table('knowledge_batch_items')
    op.drop_index('ix_knowledge_ingest_batches_channel_created', table_name='knowledge_ingest_batches')
    op.drop_index('ix_knowledge_ingest_batches_archive_sha256', table_name='knowledge_ingest_batches')
    op.drop_table('knowledge_ingest_batches')
    # ### end Alembic commands ###
